### ISSUE TITLE
Weekday is off 1

### ISSUE THREAD

**Issue by JoelBeerDe** [WesSouza/calendar-base#11]
When trying to get the days for this month (09.2022) I get an array showing that today (29.09.2022) would be a Friday but today is Thursday. This also happens if siblingMonths is true.

`{day: 29, weekDay: 4, month: 8, year: 2022}`

**Comment by hungnh17** [comment]
hey, I thought 0-6 means Sunday to Saturday? meaning week 4 is Thursday ?
0-Sunday, 1-Monday, 2-Tuesday, 3-Wednesday, 4-Thursday , 5-Friday, 6-Saturday

**Comment by WesSouza** [comment]
@JoelBeerDe `4` is correct here, as it corresponds to Thursday in the list @hungnh17 mentioned.

See this example:
https://stackblitz.com/edit/typescript-vedvgy?file=index.ts
