### ISSUE TITLE
Calendar issue

### ISSUE THREAD

**Issue by guido4000** [WesSouza/calendar-base#2]
When invoking the module with (2015,3) and {weekStart:1,siblingMonths:true} I get an array showing that today (3/13/2015) would be a Monday (weekDay 1), but it is a Friday.

```
...
{ 14: Object, day: 13, month: 3, weekDay: 1, year: 2015 },
...
```

**Comment by WesSouza** [comment]
Hey @guido4000, since I based a lot of the numeric bases from the native [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) object, when you request 2015,3 you're actually getting April:

> The value returned by `getMonth()` is an integer between 0 and 11. 0 corresponds to January, 1 to February, and so on.
> [Date.prototype.getMonth()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)

And then April 13th is a Monday.

**Comment by guido4000** [comment]
OK, thank you.
