### ISSUE TITLE
[FeatureRequest] Calendar.prototype.getWeekCalendar ( weekNumber )

### ISSUE THREAD

**Issue by MathRobin** [WesSouza/calendar-base#4]
A method which just give the days of a precise week.

**Comment by MathRobin** [comment]
Hi,

Sorry for the first non-really human message.

I continue to enjoy this great package, thanks Alain :-D 
It could  be great to have a method which just give the days of a precise week.
Is it possible ? I don't know how to do it...

**Comment by MathRobin** [comment]
Thanks again *
(sorry french auto-correct)

**Comment by WesSouza** [comment]
Hey, can you give me an example use case?

And would it work by providing a similar solution adding week numbers to the output of the current getCalendar?

**Comment by MathRobin** [comment]
Hi, off course I can. In one of my last projects I needed to introduce a feature like this one https://bootstrap-datepicker.readthedocs.org/en/latest/options.html#calendarweeks. It was for a medical center which needs to organize some events. Sometimes, knows which week is could help. Or if you want to display a week view from the month calendar.

Yes why not, like the siblings months feature, it could be an option :-D
